# Generated by Django 5.2 on 2025-04-21 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaCulto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_culto', models.DateField()),
                ('tipo_culto', models.CharField(choices=[('domingo', 'Domingo'), ('quarta', 'Quarta-feira'), ('sabado', 'Sábado')], max_length=20)),
                ('historia_criancas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historia_criancas', to=settings.AUTH_USER_MODEL)),
                ('louvor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='louvor', to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to=settings.AUTH_USER_MODEL)),
                ('pregador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pregador', to=settings.AUTH_USER_MODEL)),
                ('recepcao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepcao', to=settings.AUTH_USER_MODEL)),
                ('sonoplastia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sonoplastia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_culto'],
            },
        ),
    ]
