# Generated by Django 5.2 on 2025-04-21 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0001_initial'),
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalaculto',
            name='historia_criancas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historia_criancas', to='membros.membro'),
        ),
        migrations.AlterField(
            model_name='escalaculto',
            name='louvor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='louvor', to='membros.membro'),
        ),
        migrations.AlterField(
            model_name='escalaculto',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='membros.membro'),
        ),
        migrations.AlterField(
            model_name='escalaculto',
            name='pregador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='escalaculto',
            name='recepcao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepcao', to='membros.membro'),
        ),
        migrations.AlterField(
            model_name='escalaculto',
            name='sonoplastia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sonoplastia', to='membros.membro'),
        ),
        migrations.AlterField(
            model_name='escalaculto',
            name='tipo_culto',
            field=models.CharField(choices=[('Culto Divino', 'Culto Divino'), ('Culto Jovem', 'Culto Jovem'), ('Culto de Oração', 'Culto de Oração'), ('Culto de Gratidão', 'Culto de Gratidão'), ('Sábado Missionário', 'Sábado Missionário')], max_length=30),
        ),
    ]
